### ISSUE TITLE
CPU-ONLY mode

### ISSUE THREAD

**Issue by rttDayanara** [zeakey/LDLForest#4]
Thank you for sharing the code! I tried to run the code in CPU-ONLY mode on the Ubuntu 16 system, but there was an error (as shown below):

```
/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:1352: UserWarning: This call to matplotlib.use() has no effect because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot, or matplotlib.backends is imported for the first time.

warnings.warn(_use_error_msg)
WARNING: Logging before InitGoogleLogging() is written to STDERR F0420 12:41:10.873113 4844 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by zeakey** [comment]
Thanks for your feedback. By default caffe runs in GPU mode. If you want to excute in CPU-only mode, I think you should add `MODE: CPU` in the solver configurations.
See <https://github.com/zeakey/LDLForests/blob/master/experiments/ldl/run.py#L60-L80> for the solver arguments.

PS: There maybe other problems because we didn't test the code under CPU-only mode.

**Comment by rttDayanara** [comment]
Thanks a lot.
